package macos

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"

	toml "github.com/pelletier/go-toml/v2"

	"github.com/dnery/dotstate/dot/internal/config"
	"github.com/dnery/dotstate/dot/internal/discover"
	"github.com/dnery/dotstate/dot/internal/modules"
	"github.com/dnery/dotstate/dot/internal/redact"
	"github.com/dnery/dotstate/dot/internal/runner"
)

const generatedHeader = "# Generated by dotstate. Review before committing.\n"

// NewStateModules returns macOS non-file modules for shared apply/capture/sync
// orchestration. The modules are capture-first; system mutation is manual except
// for clone-if-missing subrepos, which are reversible by deleting the cloned path.
func NewStateModules(cfg *config.Config, r runner.Runner, home string) []modules.Module {
	if cfg == nil {
		return nil
	}
	if r == nil {
		r = runner.New()
	}
	cache := &auditCache{opts: AuditOptions{
		GOOS:         runtime.GOOS,
		Arch:         runtime.GOARCH,
		Runner:       r,
		RepoRoot:     cfg.RepoRoot(),
		HomeDir:      home,
		BrewfilePath: filepath.Join(cfg.StatePath(), "macos", "brew", "Brewfile"),
	}}
	return []modules.Module{
		newArtifactModule(surfaceBrew, filepath.Join(cfg.StatePath(), "macos", "brew", "Brewfile"), cache, renderBrewfileArtifact),
		newArtifactModule(surfaceMAS, filepath.Join(cfg.StatePath(), "macos", "mas.toml"), cache, renderMASArtifact),
		newArtifactModule(surfaceApps, filepath.Join(cfg.StatePath(), "macos", "apps.toml"), cache, renderAppsArtifact),
		newArtifactModule(surfaceDefaults, filepath.Join(cfg.StatePath(), "macos", "defaults.toml"), cache, renderDefaultsArtifact),
		newSecretsModule(filepath.Join(cfg.StatePath(), "secrets", "generated.toml"), cache),
		newSubreposModule(cfg, r, home),
	}
}

type auditCache struct {
	opts  AuditOptions
	once  sync.Once
	audit AuditEnvelope
}

func (c *auditCache) envelope(ctx context.Context) AuditEnvelope {
	c.once.Do(func() {
		c.audit = NewAudit(ctx, c.opts)
	})
	return c.audit
}

func (c *auditCache) facts(ctx context.Context, surface string) []modules.Fact {
	audit := c.envelope(ctx)
	var facts []modules.Fact
	for _, fact := range audit.Facts {
		if fact.Surface == surface {
			facts = append(facts, fact)
		}
	}
	return facts
}

func (c *auditCache) diagnostics(ctx context.Context, surface string) []modules.Diagnostic {
	audit := c.envelope(ctx)
	var diagnostics []modules.Diagnostic
	for _, diag := range audit.Diagnostics {
		if diag.Surface == surface {
			diagnostics = append(diagnostics, diag)
		}
	}
	return diagnostics
}

type artifactRenderer func([]modules.Fact) ([]byte, bool, error)

type artifactModule struct {
	surface  string
	path     string
	cache    *auditCache
	renderer artifactRenderer
	now      func() time.Time
}

func newArtifactModule(surface, path string, cache *auditCache, renderer artifactRenderer) *artifactModule {
	return &artifactModule{surface: surface, path: path, cache: cache, renderer: renderer, now: time.Now}
}

func (m *artifactModule) Surface() string { return m.surface }

func (m *artifactModule) Audit(ctx context.Context) ([]modules.Fact, []modules.Diagnostic, error) {
	return m.cache.facts(ctx, m.surface), m.cache.diagnostics(ctx, m.surface), nil
}

func (m *artifactModule) Plan(ctx context.Context, operation modules.Operation) ([]modules.Change, []modules.Diagnostic, error) {
	switch operation {
	case modules.OperationCapture:
		return m.planCapture(ctx)
	case modules.OperationApply:
		return m.planApply(ctx)
	default:
		return nil, []modules.Diagnostic{unsupportedStatePhase(m.surface, modules.PhasePlan)}, nil
	}
}

func (m *artifactModule) Backup(context.Context, []modules.Change, *modules.Plan) ([]modules.Backup, []modules.Diagnostic, error) {
	return nil, nil, nil
}

func (m *artifactModule) Apply(ctx context.Context, changes []modules.Change, plan *modules.Plan) ([]modules.Result, []modules.Diagnostic, error) {
	results := make([]modules.Result, 0, len(changes))
	for _, change := range changes {
		status := modules.StatusManual
		if change.Action == modules.ActionNoop || change.Action == modules.ActionReport {
			status = modules.StatusNoop
		}
		results = append(results, stateResult(plan, change, modules.PhaseApply, status, m.now()))
	}
	return results, nil, nil
}

func (m *artifactModule) Capture(ctx context.Context, changes []modules.Change, plan *modules.Plan) ([]modules.Result, []modules.Diagnostic, error) {
	results := make([]modules.Result, 0, len(changes))
	for _, change := range changes {
		if change.Action == modules.ActionNoop {
			results = append(results, stateResult(plan, change, modules.PhaseCapture, modules.StatusNoop, m.now()))
			continue
		}
		content, ok, err := m.renderContent(ctx)
		if err != nil {
			return results, nil, err
		}
		if !ok {
			results = append(results, stateResult(plan, change, modules.PhaseCapture, modules.StatusSkipped, m.now()))
			continue
		}
		if err := os.MkdirAll(filepath.Dir(m.path), 0o755); err != nil {
			return results, nil, err
		}
		if err := os.WriteFile(m.path, []byte(content), 0o644); err != nil {
			return results, nil, err
		}
		results = append(results, stateResult(plan, change, modules.PhaseCapture, modules.StatusCaptured, m.now()))
	}
	return results, nil, nil
}

func (m *artifactModule) Verify(ctx context.Context, operation modules.Operation, changes []modules.Change, plan *modules.Plan) ([]modules.Result, []modules.Diagnostic, error) {
	results := make([]modules.Result, 0, len(changes))
	for _, change := range changes {
		status := modules.StatusVerified
		if operation == modules.OperationCapture {
			content, ok, err := m.renderContent(ctx)
			if err != nil {
				return results, nil, err
			}
			if ok {
				current, err := os.ReadFile(m.path)
				if err != nil || string(current) != string(content) {
					status = modules.StatusFailed
				}
			}
		} else if change.Action == modules.ActionManual {
			status = modules.StatusManual
		} else if change.Action == modules.ActionNoop || change.Action == modules.ActionReport {
			status = modules.StatusNoop
		}
		results = append(results, stateResult(plan, change, modules.PhaseVerify, status, m.now()))
	}
	return results, nil, nil
}

func (m *artifactModule) Restore(context.Context, []modules.Backup) ([]modules.Result, []modules.Diagnostic, error) {
	return nil, []modules.Diagnostic{unsupportedStatePhase(m.surface, modules.PhaseRestore)}, nil
}

func (m *artifactModule) renderContent(ctx context.Context) ([]byte, bool, error) {
	facts := m.cache.facts(ctx, m.surface)
	return m.renderer(facts)
}

func (m *artifactModule) planCapture(ctx context.Context) ([]modules.Change, []modules.Diagnostic, error) {
	content, hasContent, err := m.renderContent(ctx)
	if err != nil {
		return nil, nil, err
	}
	currentContent, readErr := os.ReadFile(m.path)
	exists := readErr == nil
	action := modules.ActionNoop
	if hasContent {
		switch {
		case !exists:
			action = modules.ActionCreate
		case string(currentContent) != string(content):
			action = modules.ActionUpdate
		}
	}
	change := m.baseChange(modules.OperationCapture, action)
	change.Current = map[string]any{"path": displayArtifactPath(m.cache.opts, m.path), "exists": exists}
	if exists {
		change.Current["sha256"] = sha256Hex(currentContent)
	}
	change.Desired = map[string]any{"path": displayArtifactPath(m.cache.opts, m.path), "exists": hasContent}
	if hasContent {
		change.Desired["sha256"] = sha256Hex(content)
	}
	change.Capability = []modules.Capability{modules.CapabilityAutoApply}
	change.Risk = modules.LowRisk(true)
	return []modules.Change{change}, m.cache.diagnostics(ctx, m.surface), nil
}

func (m *artifactModule) planApply(ctx context.Context) ([]modules.Change, []modules.Diagnostic, error) {
	exists := fileExists(m.path)
	change := m.baseChange(modules.OperationApply, modules.ActionNoop)
	change.Current = map[string]any{"path": displayArtifactPath(m.cache.opts, m.path), "exists": exists}
	change.Desired = map[string]any{"path": displayArtifactPath(m.cache.opts, m.path), "exists": exists}
	change.Capability = []modules.Capability{modules.CapabilityReadOnly}
	if exists {
		change.Action = modules.ActionManual
		change.Capability = []modules.Capability{modules.CapabilityDryRunOnly, modules.CapabilityManual}
		change.Risk = modules.Risk{Level: modules.RiskMedium, Reasons: []string{"system mutation is explicit/manual for this surface"}, RequiresConfirmation: true, Reversible: false}
		change.Diagnostics = []modules.Diagnostic{manualApplyDiagnostic(m.surface, displayArtifactPath(m.cache.opts, m.path))}
	}
	return []modules.Change{change}, nil, nil
}

func (m *artifactModule) baseChange(operation modules.Operation, action modules.ChangeAction) modules.Change {
	id := m.surface + ":artifact/" + displayArtifactPath(m.cache.opts, m.path)
	return modules.Change{
		ChangeID:    fmt.Sprintf("%s:%s:%s", id, operation, action),
		Surface:     m.surface,
		ID:          id,
		Action:      action,
		Source:      modules.Source{Kind: "path", Value: displayArtifactPath(m.cache.opts, m.path)},
		ManagedBy:   []string{"dotstate"},
		Sensitivity: modules.SensitivityLocalPath,
		Confidence:  modules.ConfidenceHigh,
		Capability:  []modules.Capability{modules.CapabilityReadOnly},
		Risk:        modules.LowRisk(true),
	}
}

func newSecretsModule(path string, cache *auditCache) *artifactModule {
	return newArtifactModule(surfaceSecrets, path, cache, renderSecretsArtifact)
}

// SubrepoStatus is the read-only status for one desired subrepo entry.
type SubrepoStatus struct {
	Path      string
	URL       string
	Branch    string
	Exists    bool
	IsGitRepo bool
	Status    string
}

// SubrepoStatuses reads state/subrepos.toml and reports clone readiness without mutation.
func SubrepoStatuses(cfg *config.Config, home string) ([]SubrepoStatus, error) {
	mod := newSubreposModule(cfg, runner.New(), home)
	manifest, err := mod.readManifest()
	if err != nil {
		return nil, err
	}
	statuses := make([]SubrepoStatus, 0, len(manifest.SubRepos))
	for _, entry := range manifest.SubRepos {
		path := expandHome(entry.Path, home)
		exists := fileExists(path)
		isRepo := fileExists(filepath.Join(path, ".git"))
		status := "missing"
		switch {
		case exists && isRepo:
			status = "present"
		case exists:
			status = "blocked_existing_non_git"
		}
		statuses = append(statuses, SubrepoStatus{Path: entry.Path, URL: entry.URL, Branch: entry.Branch, Exists: exists, IsGitRepo: isRepo, Status: status})
	}
	return statuses, nil
}

type subreposModule struct {
	cfg  *config.Config
	r    runner.Runner
	home string
	now  func() time.Time
}

func newSubreposModule(cfg *config.Config, r runner.Runner, home string) *subreposModule {
	return &subreposModule{cfg: cfg, r: r, home: home, now: time.Now}
}

func (m *subreposModule) Surface() string { return surfaceSubrepos }

func (m *subreposModule) manifestPath() string {
	return filepath.Join(m.cfg.StatePath(), "subrepos.toml")
}

func (m *subreposModule) Audit(context.Context) ([]modules.Fact, []modules.Diagnostic, error) {
	manifest, err := m.readManifest()
	if err != nil {
		return nil, nil, err
	}
	facts := make([]modules.Fact, 0, len(manifest.SubRepos))
	for _, entry := range manifest.SubRepos {
		path := expandHome(entry.Path, m.home)
		facts = append(facts, modules.Fact{
			SchemaVersion: modules.SchemaFactV1,
			Surface:       surfaceSubrepos,
			ID:            "subrepos:path/" + entry.Path,
			Source:        modules.Source{Kind: "manifest", Value: "state/subrepos.toml"},
			Current:       map[string]any{"path": entry.Path, "exists": fileExists(path), "is_git_repo": fileExists(filepath.Join(path, ".git"))},
			Desired:       map[string]any{"path": entry.Path, "url": entry.URL, "branch": entry.Branch},
			ManagedBy:     []string{"dotstate", "git"},
			Sensitivity:   modules.SensitivityLocalPath,
			Confidence:    modules.ConfidenceHigh,
			Capability:    []modules.Capability{modules.CapabilityReadOnly},
			Risk:          modules.LowRisk(true),
		})
	}
	modules.SanitizeFacts(facts)
	return facts, nil, nil
}

func (m *subreposModule) Plan(ctx context.Context, operation modules.Operation) ([]modules.Change, []modules.Diagnostic, error) {
	manifest, err := m.readManifest()
	if err != nil {
		return nil, nil, err
	}
	if len(manifest.SubRepos) == 0 {
		change := m.baseChange(modules.OperationApply, modules.ActionNoop, discover.SubRepoManifest{Path: "state/subrepos.toml"})
		change.Current = map[string]any{"manifest_exists": fileExists(m.manifestPath())}
		change.Desired = map[string]any{"manifest_exists": fileExists(m.manifestPath())}
		return []modules.Change{change}, nil, nil
	}
	if operation == modules.OperationCapture {
		change := m.baseChange(operation, modules.ActionReport, discover.SubRepoManifest{Path: "state/subrepos.toml"})
		change.Current = map[string]any{"manifest": "state/subrepos.toml", "entries": len(manifest.SubRepos)}
		change.Desired = change.Current
		change.Diagnostics = []modules.Diagnostic{modules.NewDiagnostic(modules.SeverityInfo, "subrepos.capture.discover_managed", "Subrepo capture is handled by dot discover so remote URLs can be reviewed before commit.", surfaceSubrepos, "subrepos:manifest")}
		return []modules.Change{change}, nil, nil
	}
	changes := make([]modules.Change, 0, len(manifest.SubRepos))
	for _, entry := range manifest.SubRepos {
		path := expandHome(entry.Path, m.home)
		exists := fileExists(path)
		isRepo := fileExists(filepath.Join(path, ".git"))
		action := modules.ActionNoop
		capabilities := []modules.Capability{modules.CapabilityReadOnly}
		risk := modules.LowRisk(true)
		var diagnostics []modules.Diagnostic
		if !exists {
			action = modules.ActionCreate
			capabilities = []modules.Capability{modules.CapabilityAutoApply}
			risk = modules.Risk{Level: modules.RiskMedium, Reasons: []string{"clone missing subrepo"}, RequiresConfirmation: false, Reversible: true}
		} else if !isRepo {
			action = modules.ActionManual
			capabilities = []modules.Capability{modules.CapabilityManual}
			diagnostics = append(diagnostics, modules.NewDiagnostic(modules.SeverityWarning, "subrepos.destination_exists_not_git", "Subrepo destination exists but is not a git repository; clone is manual.", surfaceSubrepos, "subrepos:path/"+entry.Path))
		}
		change := m.baseChange(operation, action, entry)
		change.Current = map[string]any{"path": entry.Path, "exists": exists, "is_git_repo": isRepo}
		change.Desired = map[string]any{"path": entry.Path, "url": entry.URL, "branch": entry.Branch}
		change.Capability = capabilities
		change.Risk = risk
		change.Diagnostics = diagnostics
		changes = append(changes, change)
	}
	return changes, nil, nil
}

func (m *subreposModule) Backup(context.Context, []modules.Change, *modules.Plan) ([]modules.Backup, []modules.Diagnostic, error) {
	return nil, nil, nil
}

func (m *subreposModule) Apply(ctx context.Context, changes []modules.Change, plan *modules.Plan) ([]modules.Result, []modules.Diagnostic, error) {
	results := make([]modules.Result, 0, len(changes))
	for _, change := range changes {
		if change.Action != modules.ActionCreate {
			status := modules.StatusNoop
			if change.Action == modules.ActionManual {
				status = modules.StatusManual
			}
			results = append(results, stateResult(plan, change, modules.PhaseApply, status, m.now()))
			continue
		}
		url, _ := stringFromMap(change.Desired, "url")
		pathRel, _ := stringFromMap(change.Desired, "path")
		branch, _ := stringFromMap(change.Desired, "branch")
		dest := expandHome(pathRel, m.home)
		args := []string{"clone"}
		if branch != "" {
			args = append(args, "--branch", branch)
		}
		args = append(args, url, dest)
		if _, err := m.r.Run(ctx, "", "git", args...); err != nil {
			return results, nil, err
		}
		results = append(results, stateResult(plan, change, modules.PhaseApply, modules.StatusApplied, m.now()))
	}
	return results, nil, nil
}

func (m *subreposModule) Capture(ctx context.Context, changes []modules.Change, plan *modules.Plan) ([]modules.Result, []modules.Diagnostic, error) {
	results := make([]modules.Result, 0, len(changes))
	for _, change := range changes {
		results = append(results, stateResult(plan, change, modules.PhaseCapture, modules.StatusSkipped, m.now()))
	}
	return results, nil, nil
}

func (m *subreposModule) Verify(ctx context.Context, operation modules.Operation, changes []modules.Change, plan *modules.Plan) ([]modules.Result, []modules.Diagnostic, error) {
	results := make([]modules.Result, 0, len(changes))
	for _, change := range changes {
		status := modules.StatusVerified
		if operation == modules.OperationApply && change.Action == modules.ActionCreate {
			pathRel, _ := stringFromMap(change.Desired, "path")
			if !fileExists(filepath.Join(expandHome(pathRel, m.home), ".git")) {
				status = modules.StatusFailed
			}
		} else if change.Action == modules.ActionManual {
			status = modules.StatusManual
		} else if change.Action == modules.ActionNoop || change.Action == modules.ActionReport {
			status = modules.StatusNoop
		}
		results = append(results, stateResult(plan, change, modules.PhaseVerify, status, m.now()))
	}
	return results, nil, nil
}

func (m *subreposModule) Restore(context.Context, []modules.Backup) ([]modules.Result, []modules.Diagnostic, error) {
	return nil, []modules.Diagnostic{unsupportedStatePhase(surfaceSubrepos, modules.PhaseRestore)}, nil
}

func (m *subreposModule) readManifest() (discover.SubReposManifest, error) {
	data, err := os.ReadFile(m.manifestPath())
	if err != nil {
		if os.IsNotExist(err) {
			return discover.SubReposManifest{}, nil
		}
		return discover.SubReposManifest{}, err
	}
	if strings.TrimSpace(string(data)) == "" {
		return discover.SubReposManifest{}, nil
	}
	var manifest discover.SubReposManifest
	if err := toml.Unmarshal(data, &manifest); err != nil {
		return discover.SubReposManifest{}, err
	}
	return manifest, nil
}

func (m *subreposModule) baseChange(operation modules.Operation, action modules.ChangeAction, entry discover.SubRepoManifest) modules.Change {
	id := "subrepos:path/" + entry.Path
	return modules.Change{
		ChangeID:    fmt.Sprintf("%s:%s:%s", id, operation, action),
		Surface:     surfaceSubrepos,
		ID:          id,
		Action:      action,
		Source:      modules.Source{Kind: "manifest", Value: "state/subrepos.toml"},
		ManagedBy:   []string{"dotstate", "git"},
		Sensitivity: modules.SensitivityLocalPath,
		Confidence:  modules.ConfidenceHigh,
		Capability:  []modules.Capability{modules.CapabilityReadOnly},
		Risk:        modules.LowRisk(true),
	}
}

func renderBrewfileArtifact(facts []modules.Fact) ([]byte, bool, error) {
	var taps, formulae, casks []string
	for _, fact := range facts {
		name, _ := stringFromMap(fact.Current, "name")
		switch {
		case strings.HasPrefix(fact.ID, "brew:tap/"):
			taps = append(taps, name)
		case strings.HasPrefix(fact.ID, "brew:formula/"):
			formulae = append(formulae, name)
		case strings.HasPrefix(fact.ID, "brew:cask/"):
			casks = append(casks, name)
		}
	}
	if len(taps)+len(formulae)+len(casks) == 0 {
		return nil, false, nil
	}
	sort.Strings(taps)
	sort.Strings(formulae)
	sort.Strings(casks)
	var b strings.Builder
	b.WriteString(generatedHeader)
	for _, tap := range taps {
		fmt.Fprintf(&b, "tap %q\n", tap)
	}
	for _, formula := range formulae {
		fmt.Fprintf(&b, "brew %q\n", formula)
	}
	for _, cask := range casks {
		fmt.Fprintf(&b, "cask %q\n", cask)
	}
	return []byte(b.String()), true, nil
}

type masArtifact struct {
	Apps []masArtifactApp `toml:"app"`
}

type masArtifactApp struct {
	ID      string `toml:"id"`
	Name    string `toml:"name,omitempty"`
	Version string `toml:"version,omitempty"`
}

func renderMASArtifact(facts []modules.Fact) ([]byte, bool, error) {
	artifact := masArtifact{}
	for _, fact := range facts {
		id, _ := stringFromMap(fact.Current, "id")
		if id == "" {
			continue
		}
		name, _ := stringFromMap(fact.Current, "name")
		version, _ := stringFromMap(fact.Current, "version")
		artifact.Apps = append(artifact.Apps, masArtifactApp{ID: id, Name: name, Version: version})
	}
	sort.Slice(artifact.Apps, func(i, j int) bool { return artifact.Apps[i].ID < artifact.Apps[j].ID })
	if len(artifact.Apps) == 0 {
		return nil, false, nil
	}
	return marshalTOMLArtifact(artifact)
}

type appsArtifact struct {
	Apps []appsArtifactApp `toml:"app"`
}

type appsArtifactApp struct {
	BundleID   string `toml:"bundle_id"`
	Name       string `toml:"name,omitempty"`
	Version    string `toml:"version,omitempty"`
	SourceHint string `toml:"source_hint,omitempty"`
	Path       string `toml:"path,omitempty"`
}

func renderAppsArtifact(facts []modules.Fact) ([]byte, bool, error) {
	artifact := appsArtifact{}
	for _, fact := range facts {
		bundleID, _ := stringFromMap(fact.Current, "bundle_id")
		if bundleID == "" {
			continue
		}
		name, _ := stringFromMap(fact.Current, "name")
		version, _ := stringFromMap(fact.Current, "version")
		sourceHint, _ := stringFromMap(fact.Current, "source_hint")
		path, _ := stringFromMap(fact.Current, "path")
		artifact.Apps = append(artifact.Apps, appsArtifactApp{BundleID: bundleID, Name: name, Version: version, SourceHint: sourceHint, Path: path})
	}
	sort.Slice(artifact.Apps, func(i, j int) bool { return artifact.Apps[i].BundleID < artifact.Apps[j].BundleID })
	if len(artifact.Apps) == 0 {
		return nil, false, nil
	}
	return marshalTOMLArtifact(artifact)
}

type defaultsArtifact struct {
	Defaults []defaultsArtifactEntry `toml:"default"`
}

type defaultsArtifactEntry struct {
	Domain string `toml:"domain"`
	Key    string `toml:"key"`
	Value  string `toml:"value"`
}

func renderDefaultsArtifact(facts []modules.Fact) ([]byte, bool, error) {
	artifact := defaultsArtifact{}
	for _, fact := range facts {
		domain, _ := stringFromMap(fact.Current, "domain")
		key, _ := stringFromMap(fact.Current, "key")
		value, ok := stringFromMap(fact.Current, "value")
		if domain == "" || key == "" || !ok {
			continue
		}
		artifact.Defaults = append(artifact.Defaults, defaultsArtifactEntry{Domain: domain, Key: key, Value: value})
	}
	sort.Slice(artifact.Defaults, func(i, j int) bool {
		if artifact.Defaults[i].Domain != artifact.Defaults[j].Domain {
			return artifact.Defaults[i].Domain < artifact.Defaults[j].Domain
		}
		return artifact.Defaults[i].Key < artifact.Defaults[j].Key
	})
	if len(artifact.Defaults) == 0 {
		return nil, false, nil
	}
	return marshalTOMLArtifact(artifact)
}

type secretsArtifact struct {
	Policy secretsPolicy `toml:"policy"`
}

type secretsPolicy struct {
	SecretValuesSerialized bool   `toml:"secret_values_serialized"`
	KeychainContentsRead   bool   `toml:"keychain_contents_read"`
	PrivateOutputDir       string `toml:"private_output_dir"`
	ReferenceScheme        string `toml:"reference_scheme"`
}

func renderSecretsArtifact([]modules.Fact) ([]byte, bool, error) {
	return marshalTOMLArtifact(secretsArtifact{Policy: secretsPolicy{PrivateOutputDir: "state/private/", ReferenceScheme: "op://"}})
}

func marshalTOMLArtifact(v any) ([]byte, bool, error) {
	data, err := toml.Marshal(v)
	if err != nil {
		return nil, false, err
	}
	return append([]byte(generatedHeader), data...), true, nil
}

func manualApplyDiagnostic(surface, artifact string) modules.Diagnostic {
	diag := modules.NewDiagnostic(modules.SeverityInfo, "macos."+surface+".apply_manual", "Desired artifact is captured, but system mutation for this surface is explicit/manual in this release.", surface, surface+":artifact/"+artifact)
	diag.Capability = []modules.Capability{modules.CapabilityDryRunOnly, modules.CapabilityManual}
	diag.Remediation = "Review the artifact and apply it with the native manager until this module has backup/restore/idempotency coverage."
	return diag
}

func unsupportedStatePhase(surface string, phase modules.Phase) modules.Diagnostic {
	diag := modules.NewDiagnostic(modules.SeverityInfo, "macos."+surface+"."+string(phase)+"_unsupported", "This non-file macOS module does not support the requested phase yet.", surface, surface+":"+string(phase))
	diag.Capability = []modules.Capability{modules.CapabilityUnsupported}
	return diag
}

func stateResult(plan *modules.Plan, change modules.Change, phase modules.Phase, status modules.ResultStatus, at time.Time) modules.Result {
	return modules.Result{
		SchemaVersion: modules.SchemaResultV1,
		RunID:         modules.Timestamp(at),
		PlanID:        plan.PlanID,
		Phase:         phase,
		Surface:       change.Surface,
		ID:            change.ID,
		ChangeID:      change.ChangeID,
		Source:        change.Source,
		Current:       change.Current,
		Desired:       change.Desired,
		ManagedBy:     change.ManagedBy,
		Sensitivity:   change.Sensitivity,
		Confidence:    change.Confidence,
		Capability:    change.Capability,
		Risk:          change.Risk,
		Status:        status,
		StartedAt:     modules.Timestamp(at),
		EndedAt:       modules.Timestamp(at),
		Diagnostics:   change.Diagnostics,
	}
}

func sha256Hex(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

func stringFromMap(values map[string]any, key string) (string, bool) {
	if values == nil {
		return "", false
	}
	value, ok := values[key]
	if !ok || value == nil {
		return "", false
	}
	switch v := value.(type) {
	case string:
		return strings.TrimSpace(v), true
	default:
		return strings.TrimSpace(fmt.Sprint(v)), true
	}
}

func expandHome(path, home string) string {
	path = strings.TrimSpace(path)
	if strings.HasPrefix(path, "~/") || strings.HasPrefix(path, `~\`) {
		return filepath.Join(home, path[2:])
	}
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Join(home, path)
}

func redactRemote(raw string) string {
	return redact.Text(raw)
}
