# golangci-lint configuration
# Run with: golangci-lint run
# Install: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

run:
  timeout: 5m
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional quality linters
    - bodyclose        # Check HTTP response body is closed
    - dupl             # Detect duplicate code
    - errorlint        # Find issues with error wrapping
    - exhaustive       # Check exhaustiveness of enum switches
    - gocognit         # Cognitive complexity
    - goconst          # Find repeated strings that could be constants
    - gocritic         # Opinionated linter with many checks
    - gofmt            # Check formatting
    - goimports        # Check imports ordering
    - gosec            # Security checker
    - misspell         # Spell checker
    - nakedret         # Find naked returns in large functions
    - nilerr           # Find code returning nil error with non-nil value
    - noctx            # Find HTTP requests without context
    - prealloc         # Find slice declarations that could be preallocated
    - predeclared      # Find shadowed predeclared identifiers
    - revive           # Fast, configurable linter
    - stylecheck       # Style checker
    - tenv             # Detect os.Setenv in tests
    - testableexamples # Check testable examples
    - tparallel        # Detect inappropriate use of t.Parallel()
    - unconvert        # Remove unnecessary type conversions
    - unparam          # Find unused function parameters
    - whitespace       # Detect leading/trailing whitespace

linters-settings:
  gocognit:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/dnery/dotstate

  gosec:
    excludes:
      - G104  # Errors unhandled (too noisy, errcheck covers this better)
      - G304  # File path provided as taint input (common in CLI tools)

  nakedret:
    max-func-lines: 30

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      - name: var-naming

  stylecheck:
    checks:
      - all
      - -ST1000  # Package comments (too strict for internal packages)

issues:
  exclude-rules:
    # Test files can have longer functions and more complexity
    - path: _test\.go
      linters:
        - dupl
        - gocognit
        - goconst
        - gosec

    # Main entry point is allowed to be simple
    - path: cmd/dot/main\.go
      linters:
        - gocognit

  max-issues-per-linter: 50
  max-same-issues: 10
